const petImages: Record<number, string> = {
    1: "../public/assets/images/lucas.png",
    2: "../public/assets/images/andy.png",
    3: "../public/assets/images/glen.png",
    4: "../public/assets/images/mike.png",
    5: "../public/assets/images/eagles.png",
    6: "../public/assets/images/koala.png",
    7: "../public/assets/images/lion.png",
    8: "../public/assets/images/tiger.png",
    9: "../public/assets/images/bella.png",
    10: "../public/assets/images/rocky.png",
    11: "../public/assets/images/zara.png",
    12: "../public/assets/images/neptune.png",
    13: "../public/assets/images/amber.png",
    14: "../public/assets/images/duke.png",
    15: "../public/assets/images/sunny.png",
    16: "../public/assets/images/koda.png",
    17: "../public/assets/images/marina.png",
    18: "../public/assets/images/oscar.png",
    19: "../public/assets/images/polarbear.png",
    20: "../public/assets/images/jasper.png",
    21: "../public/assets/images/riko.png",
    22: "../public/assets/images/thunder.png",
    23: "../public/assets/images/luna.png",
    24: "../public/assets/images/atlas.png",
    25: "../public/assets/images/ruby.png",
    26: "../public/assets/images/titan.png",
    27: "../public/assets/images/olive.png",
    28: "../public/assets/images/blaze.png",
};

export default petImages;