const petImages: Record<number, string> = {
    1: "/assets/images/lucas.png",
    2: "/assets/images/andy.png",
    3: "/assets/images/glen.png",
    4: "/assets/images/mike.png",
    5: "/assets/images/eagles.png",
    6: "/assets/images/koala.png",
    7: "/assets/images/lion.png",
    8: "/assets/images/tiger.png",
    9: "/assets/images/bella.png",
    10: "/assets/images/rocky.png",
    11: "/assets/images/zara.png",
    12: "/assets/images/neptune.png",
    13: "/assets/images/amber.png",
    14: "/assets/images/duke.png",
    15: "/assets/images/sunny.png",
    16: "/assets/images/koda.png",
    17: "/assets/images/marina.png",
    18: "/assets/images/oscar.png",
    19: "/assets/images/polarbear.png",
    20: "/assets/images/jasper.png",
    21: "/assets/images/riko.png",
    22: "/assets/images/thunder.png",
    23: "/assets/images/luna.png",
    24: "/assets/images/atlas.png",
    25: "/assets/images/ruby.png",
    26: "/assets/images/titan.png",
    27: "/assets/images/olive.png",
    28: "/assets/images/blaze.png",
};

export default petImages;